"""
DataScout — Visualization Component.

Downloads and displays chart images generated by the Code Interpreter.
Supports both direct image bytes (from Bedrock stream) and S3 URI downloads.
"""

from typing import List

import streamlit as st

try:
    from services.s3_handler import S3Handler
except ImportError:
    from streamlit_app.services.s3_handler import S3Handler


def render_visualization(s3_uris: List[str] = None,
                         chart_images: list = None,
                         s3_handler: S3Handler = None) -> None:
    """Display chart images from direct bytes or S3 downloads.

    Args:
        s3_uris: List of S3 URIs pointing to chart PNG images (fallback).
        chart_images: List of dicts with 'bytes', 'name', 'type' keys
                      (direct from Code Interpreter stream).
        s3_handler: Optional S3Handler instance; creates one if not provided.
    """
    displayed = 0

    # ── Priority 1: Direct chart images from Code Interpreter ──────────
    if chart_images:
        for i, img in enumerate(chart_images):
            image_bytes = img.get('bytes', b'')
            file_name = img.get('name', f'chart_{i + 1}.png')
            if image_bytes:
                st.image(
                    image_bytes,
                    caption=f"Chart {i + 1}",
                    width="stretch"
                )
                st.download_button(
                    label=f"📥 Download Chart {i + 1}",
                    data=image_bytes,
                    file_name=file_name,
                    mime="image/png",
                    key=f"download_chart_direct_{i}"
                )
                displayed += 1

    # ── Priority 2: Download from S3 URIs (fallback) ───────────────────
    if s3_uris and displayed == 0:
        if s3_handler is None:
            s3_handler = S3Handler()

        for i, uri in enumerate(s3_uris):
            try:
                image_bytes = s3_handler.download_artifact(uri)
                st.image(
                    image_bytes,
                    caption=f"Chart {displayed + 1}",
                    width="stretch"
                )
                st.download_button(
                    label=f"📥 Download Chart {displayed + 1}",
                    data=image_bytes,
                    file_name=f"datascout_chart_{displayed + 1}.png",
                    mime="image/png",
                    key=f"download_chart_s3_{i}_{hash(uri)}"
                )
                displayed += 1
            except Exception as e:
                st.warning(f"⚠️ Could not load chart from S3: {str(e)}")

    if displayed == 0:
        st.info("No visualizations were generated.")
