"""
DataScout — Visualization Component.

Downloads and displays chart images generated by the Code Interpreter.
"""

from typing import List

import streamlit as st

from streamlit_app.services.s3_handler import S3Handler


def render_visualization(s3_uris: List[str], s3_handler: S3Handler = None) -> None:
    """Download and display chart images from S3.

    Features:
        - Auto-download from S3
        - Full-width image display
        - Download button for each chart
        - Caption with chart description

    Args:
        s3_uris: List of S3 URIs pointing to chart PNG images.
        s3_handler: Optional S3Handler instance; creates one if not provided.
    """
    if not s3_uris:
        st.info("No visualizations were generated.")
        return

    if s3_handler is None:
        s3_handler = S3Handler()

    for i, uri in enumerate(s3_uris):
        try:
            image_bytes = s3_handler.download_artifact(uri)
            st.image(
                image_bytes,
                caption=f"Chart {i + 1}",
                use_container_width=True
            )
            st.download_button(
                label=f"📥 Download Chart {i + 1}",
                data=image_bytes,
                file_name=f"datascout_chart_{i + 1}.png",
                mime="image/png",
                key=f"download_chart_{i}_{hash(uri)}"
            )
        except Exception as e:
            st.warning(f"⚠️ Could not load chart {i + 1}: {str(e)}")
